// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT5HTrn5anC7bwfdLx8AmF-MafDcNlIzg',
    appId: '1:1026451165224:web:dc442a4c04fe8cf7be651d',
    messagingSenderId: '1026451165224',
    projectId: 'easy-mind-51834',
    authDomain: 'easy-mind-51834.firebaseapp.com',
    storageBucket: 'easy-mind-51834.firebasestorage.app',
    measurementId: 'G-LELN1NTF6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPUg22bVF57bbxPo5v8fIjKsSo6yODS3k',
    appId: '1:1026451165224:android:4b1d0898cac03154be651d',
    messagingSenderId: '1026451165224',
    projectId: 'easy-mind-51834',
    storageBucket: 'easy-mind-51834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8WWbxFCJbIaHNUjmRLoDSeXgczXoUYk',
    appId: '1:1026451165224:ios:77a44880f1294cd8be651d',
    messagingSenderId: '1026451165224',
    projectId: 'easy-mind-51834',
    storageBucket: 'easy-mind-51834.firebasestorage.app',
    iosClientId: '1026451165224-hqjnnrb5cr89ppj502in5ktl6179je4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.easymind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8WWbxFCJbIaHNUjmRLoDSeXgczXoUYk',
    appId: '1:1026451165224:ios:77a44880f1294cd8be651d',
    messagingSenderId: '1026451165224',
    projectId: 'easy-mind-51834',
    storageBucket: 'easy-mind-51834.firebasestorage.app',
    iosClientId: '1026451165224-hqjnnrb5cr89ppj502in5ktl6179je4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.easymind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT5HTrn5anC7bwfdLx8AmF-MafDcNlIzg',
    appId: '1:1026451165224:web:ce6a172499630c4ebe651d',
    messagingSenderId: '1026451165224',
    projectId: 'easy-mind-51834',
    authDomain: 'easy-mind-51834.firebaseapp.com',
    storageBucket: 'easy-mind-51834.firebasestorage.app',
    measurementId: 'G-T9GZBVVRYJ',
  );

}